# Generated by Django 4.1.2 on 2022-10-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecturer',
            new_name='Instructor',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='lecturer_password',
            new_name='instructor_password',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='lecturer',
            new_name='instructor',
        ),
    ]
