# Generated by Django 4.1.2 on 2022-10-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcapp', '0002_rename_lecturer_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcapp.lecture')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcapp.question')),
            ],
        ),
    ]
