# Generated by Django 4.1.3 on 2022-11-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcapp', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_date',
            field=models.DateTimeField(blank=True, verbose_name='date of lecture'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
