# Generated by Django 4.1.3 on 2022-11-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcapp', '0008_alter_lecture_lecture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_date',
            field=models.DateField(blank=True, verbose_name='date of lecture'),
        ),
    ]
