# Generated by Django 4.1.3 on 2023-02-13 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tcapp', '0015_alter_threshold_orange_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='instructor',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
