# Generated by Django 4.1.3 on 2023-02-19 19:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tcapp', '0016_alter_threshold_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Module',
            new_name='User_Module',
        ),
        migrations.RenameField(
            model_name='user_module',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='threshold',
            name='orange_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='red_percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='yellow_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
