# Generated by Django 4.1.3 on 2023-02-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcapp', '0017_rename_student_module_user_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_time', models.DateTimeField(verbose_name='date and time of reset')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcapp.lecture')),
            ],
        ),
    ]
