# Generated by Django 4.1.3 on 2023-02-24 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tcapp', '0018_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset',
            name='instructor',
            field=models.ForeignKey(default=119, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
