# Generated by Django 4.1.3 on 2023-04-23 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tcapp", "0020_remove_question_lecture_delete_choice_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lecture",
            old_name="lecture_name",
            new_name="lecture_shortname",
        ),
    ]
